apiVersion: apps/v1
kind: Deployment
metadata:
  name: sba-frontend-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sba-frontend
      release: v2
  template:
    metadata:
      labels:
        app: sba-frontend
        release: v2
    spec:
      containers:
      - image: harishpandu43/sba-frontend:blue
        name: sba-frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: nginx
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: ambassador-nginx-config
